import '@fontsource/firago'
import '@fontsource/firago/400-italic.css'
import '@fontsource/firago/400.css'
import '@fontsource/firago/500.css'
import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
